---
- name: Configure Puma service
  hosts: app
  become: true

  roles:
    - app
    - jdauphant.nginx
      nginx_sites:
        default:
          - listen 80
          - server_name "reddit"
          - location / {
              proxy_pass http://127.0.0.1:9292;
            }

