---
- name: Deploy app
  hosts: all
  become: true
  tasks:
    - name: apt update
      apt:
        update_cache=yes
        force_apt_get=yes
    - name: Install needed apps
      apt:
        name={{ item }}
        state=present
      loop:
        - ruby-full
        - ruby-bundler
        - build-essential
        - git

