---
- name: Install mongodb 3.2
  hosts: all
  become: true
  tasks:
    - name: Add APT key
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com

    - name: Add Reposytory
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
    
    - name: apt update
      apt:
        update_cache=yes
        force_apt_get=yes

    - name: Install mongodb package
      apt:
        name: mongodb-org
        allow_unauthenticated: yes
        force_apt_get: yes
        state: present

    - name: Enable and start mongod
      systemd:
        name: mongod
        enabled: yes

